#!/bin/bash

new_version=$(curl -sL "https://plex.tv/api/downloads/5.json" | grep -oP '"version":"\K[^"]+' | head -n 1)

installed_version=$(/usr/lib/plexmediaserver/'Plex Media Server' --version | sed 's/^v//')

fecha_hora=$(date +"%d/%m/%Y %H:%M")

if [[ $new_version != $installed_version ]]; then
    echo "$fecha_hora La versión actual es $installed_version, se va a proceder a actualizar a la $new_version." >> update_plex.log
    wget https://downloads.plex.tv/plex-media-server-new/${new_version}/debian/plexmediaserver_${new_version}_amd64.deb
    dpkg -i plexmediaserver_${new_version}_amd64.deb
    rm plexmediaserver_${new_version}_amd64.deb
else
    echo "$fecha_hora La versión actual es $installed_version, no es necesario actualizar." >> update_plex.log
fi
